# Generated by Django 3.0.5 on 2020-04-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_category',
            field=models.CharField(default='Undefined', max_length=100),
        ),
    ]
