# Generated by Django 3.0.5 on 2020-04-20 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_tasks_task_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task_category',
            new_name='category',
        ),
    ]
