# Generated by Django 3.0.5 on 2020-04-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20200420_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('CO', 'Completed'), ('PE', 'Pending'), ('CA', 'Canceled')], default='Pending', max_length=2),
        ),
    ]
