# Generated by Django 3.0.5 on 2020-04-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
